---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-rhc-intro"
      label: "Rhc Intro"
      solveButton: false
    - name: "02-connecting"
      label: "Connecting"
      solveButton: false
    - name: "03-insights"
      label: "Insights"
      solveButton: false
    - name: "04-insights-vuln"
      label: "Insights Vuln"
      solveButton: false
    - name: "05-conclusion"
      label: "Conclusion"
      solveButton: false

tabs:
  - name: ">_ terminal"
    url: /wetty_rhel/ssh/root
