:imagedir: ../assets/images

= Introduction to rhc

`+rhc+` is a tool used to register systems to Red Hat and connect them
to the Hybrid Cloud Console at the same time. This is useful because the
Hybrid Cloud Console is where you’ll find Red Hat Insights. Insights is
a powerful tool that you get simply by virtue of having a RHEL
subscription, even if you’re using RHEL through your cloud provider’s
pay-as-you-go program.

`+rhc+` is already installed for you on this system, but in some cases
you may need to install it before you can proceed. In a pay as you go
cloud model you’ll simply be able to `+dnf install rhc+` and it will be
pulled from your cloud providers repositories. A minimal RHEL install
however may not have `+rhc+` installed. In which case you will either
have to add it at install time, install it using your RHEL install
media, or subscribe your system using `+subscription manager+` to
install it.

NOTE: For reference, the official documentation for `+rhc+` is available at https://access.redhat.com/documentation/en-us/red_hat_insights/2025/html-single/red_hat_remote_host_configuration_utility/index[Red Hat Remote Host Configuration Utility].

Let’s have a look at the options `+rhc+` includes.

[source,bash,run]
----
rhc --help
----

As you can see, there are several options at our disposal, including
several ways to automate the registration process.

In the next step, we’ll register a system to Red Hat using `+rhc+`
